# Generated by Django 5.2.5 on 2025-09-02 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='chassinumber',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
