# Generated by Django 5.2.5 on 2025-09-06 07:06

import car.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_carlist_chassinumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='chassinumber',
            field=models.CharField(blank=True, max_length=100, null=True, validators=[car.models.chassivalidator]),
        ),
    ]
