# Generated by Django 5.2.5 on 2025-10-26 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_review_api_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
