# Generated by Django 5.2.5 on 2025-11-08 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0008_alter_review_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='features',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='carlist',
            name='showroom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='car.showroom'),
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='car_images/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='car.carlist')),
            ],
        ),
    ]
