# Generated by Django 5.2.5 on 2025-11-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0010_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
